apiVersion: v1
kind: ConfigMap
metadata:
  name: hermes-operator-settings
  labels:
    app.kubernetes.io/name: hermes-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  network-policy.yaml: |
{{ toYaml .Values.networkPolicy | indent 4 }}
